"""empty message

Revision ID: 5c7f6756c6c4
Revises: f808fbe3fb2d
Create Date: 2024-12-28 19:08:08.798615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7f6756c6c4'
down_revision = 'f808fbe3fb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
