"""empty message

Revision ID: 847dab3e1166
Revises: b9142d20bfd2
Create Date: 2024-12-28 16:35:10.415883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847dab3e1166'
down_revision = 'b9142d20bfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('details', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
