"""empty message

Revision ID: 656b6656c995
Revises: 
Create Date: 2024-12-15 10:28:39.186035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656b6656c995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
