"""empty message

Revision ID: 995ead7b9994
Revises: bad7ff0eb23e
Create Date: 2024-12-21 16:37:31.050335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995ead7b9994'
down_revision = 'bad7ff0eb23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('raw')

    # ### end Alembic commands ###
